# Generated by Django 5.1.6 on 2025-05-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_options_remove_comment_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, help_text='评论者邮箱', max_length=254),
        ),
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.CharField(blank=True, help_text='评论者昵称', max_length=50),
        ),
    ]
