# Generated by Django 5.1.15 on 2026-09-27 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0007_commentreadstate"),
        ("dynamic", "0008_dynamiclike"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["dynamic", "status", "-created_at"],
                name="comment_dyn_status_idx",
            ),
        ),
    ]
