# Generated by Django 5.1.6 on 2025-04-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options_category_parent_category_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='create_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='update_time',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='分类描述'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='分类名称', max_length=50, unique=True),
        ),
    ]
