# Generated by Django 5.1.6 on 2025-05-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort', 'id'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
