# Generated by Django 5.1.6 on 2025-05-12 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='分类名称', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='分类描述')),
                ('sort', models.IntegerField(default=0, help_text='排序')),
                ('status', models.BooleanField(default=True, help_text='状态：True-启用，False-禁用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '文件分类',
                'verbose_name_plural': '文件分类',
                'db_table': 'file_category',
                'ordering': ['sort', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='标签名称', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='标签描述')),
                ('sort', models.IntegerField(default=0, help_text='排序')),
                ('status', models.BooleanField(default=True, help_text='状态：True-启用，False-禁用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '文件标签',
                'verbose_name_plural': '文件标签',
                'db_table': 'file_tag',
                'ordering': ['sort', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='description',
            field=models.TextField(blank=True, help_text='文件描述'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='download_count',
            field=models.PositiveIntegerField(default=0, help_text='下载次数'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='是否公开'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file_size',
            field=models.BigIntegerField(help_text='文件大小(字节)'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file_type',
            field=models.CharField(choices=[('image', '图片'), ('video', '视频'), ('audio', '音频'), ('document', '文档'), ('other', '其他')], help_text='文件类型', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file_url',
            field=models.CharField(help_text='文件URL', max_length=500),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='upload.filecategory'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='files', to='upload.filetag'),
        ),
    ]
