# Generated by Django 5.1.15 on 2026-09-27 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0006_move_public_file_links_to_api_files"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="uploadfile",
            index=models.Index(fields=["-created_at"], name="upload_created_idx"),
        ),
        migrations.AddIndex(
            model_name="uploadfile",
            index=models.Index(
                fields=["file_type", "-created_at"], name="upload_type_created_idx"
            ),
        ),
    ]
