# Generated by Django 5.1.6 on 2026-07-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='device_model',
            field=models.CharField(default='未识别设备', max_length=120),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='device_type',
            field=models.CharField(default='other', max_length=20),
        ),
    ]
