# Generated by Django 5.1.6 on 2026-09-04 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_log', '0002_accesslog_device_model_accesslog_device_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IpGeoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(help_text='CIDR 网段', max_length=64, unique=True)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('region', models.CharField(blank=True, default='', max_length=120)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('isp', models.CharField(blank=True, default='', max_length=160)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('version', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['network'],
            },
        ),
        migrations.CreateModel(
            name='IpSecurityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(db_index=True, help_text='IP 或 CIDR', max_length=64)),
                ('rule_type', models.CharField(choices=[('whitelist', '可信白名单'), ('blacklist', '恶意黑名单'), ('ban', '封禁'), ('rate_limit', '限流')], max_length=20)),
                ('attack_level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='medium', max_length=12)),
                ('requests', models.PositiveIntegerField(blank=True, help_text='限流请求数', null=True)),
                ('window_seconds', models.PositiveIntegerField(blank=True, help_text='限流窗口秒数', null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_permanent', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('active', '生效'), ('revoked', '已撤销')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_rules_created', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_rules_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IpRateBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('window_start', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_buckets', to='access_log.ipsecurityrule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('rule', 'ip_address', 'window_start'), name='unique_ip_rate_window')],
            },
        ),
    ]
