# Generated by Django 5.1.15 on 2026-09-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_log', '0003_ipgeorecord_ipsecurityrule_ipratebucket'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpGeoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('data', models.JSONField(default=dict)),
                ('lookup_ok', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
