# Generated by Django 5.1.6 on 2025-04-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='audio_data',
            field=models.TextField(blank=True, null=True, verbose_name='音频数据'),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='images_data',
            field=models.TextField(blank=True, null=True, verbose_name='图片数据'),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='type',
            field=models.CharField(choices=[('text', '文本'), ('image', '图片'), ('audio', '音频'), ('video', '视频')], default='text', max_length=10, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='video_data',
            field=models.TextField(blank=True, null=True, verbose_name='视频数据'),
        ),
    ]
