# Generated by Django 5.1.6 on 2025-04-29 14:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_options_and_more'),
        ('dynamic', '0002_dynamic_audio_data_dynamic_images_data_dynamic_type_and_more'),
        ('tag', '0003_alter_tag_options_rename_create_time_tag_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamic',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='dynamic',
            name='audio_data',
        ),
        migrations.RemoveField(
            model_name='dynamic',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='dynamic',
            name='images_data',
        ),
        migrations.RemoveField(
            model_name='dynamic',
            name='title',
        ),
        migrations.RemoveField(
            model_name='dynamic',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='dynamic',
            name='video_data',
        ),
        migrations.RemoveField(
            model_name='dynamic',
            name='views',
        ),
        migrations.AddField(
            model_name='dynamic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dynamic',
            name='media_urls',
            field=models.JSONField(blank=True, default=list, help_text='媒体文件URL数组'),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamics', to='category.category'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='content',
            field=models.TextField(help_text='动态内容'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='dynamics', to='tag.tag'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='type',
            field=models.CharField(choices=[('text', '文本'), ('image', '图片'), ('audio', '音频'), ('video', '视频')], default='text', max_length=10),
        ),
        migrations.AddIndex(
            model_name='dynamic',
            index=models.Index(fields=['type', 'status'], name='dynamic_type_98edd5_idx'),
        ),
        migrations.AddIndex(
            model_name='dynamic',
            index=models.Index(fields=['created_at'], name='dynamic_created_4618b0_idx'),
        ),
        migrations.AlterModelTable(
            name='dynamic',
            table='dynamic',
        ),
    ]
