# Generated by Django 5.1.6 on 2025-05-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0003_alter_dynamic_options_remove_dynamic_audio_data_and_more'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='files',
            field=models.ManyToManyField(blank=True, help_text='关联的文件', related_name='dynamics', to='upload.uploadfile'),
        ),
    ]
