# Generated by Django 5.1.6 on 2025-05-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0004_dynamic_files'),
        ('upload', '0001_initial'),
    ]

    # 0004_dynamic_files already added this field. Keeping this migration as
    # an explicit no-op preserves the migration graph for deployed databases
    # while allowing a fresh database to be created successfully.
    operations = []
