# Generated by Django 5.1.6 on 2025-05-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0004_dynamic_files'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='files',
            field=models.ManyToManyField(blank=True, help_text='关联的文件', related_name='dynamics', to='upload.uploadfile'),
        ),
    ]
