# Generated by Django 5.1.6 on 2025-05-15 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0005_auto_20250513_2114'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_dynamics', to=settings.AUTH_USER_MODEL),
        ),
    ]
