# Generated by Django 5.1.6 on 2025-05-15 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0006_add_like_count_and_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, help_text='动态标题', max_length=200),
            preserve_default=False,
        ),
    ]
