# Generated by Django 5.1.6 on 2025-05-20 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0007_add_title_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dynamic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_likes', to='dynamic.dynamic')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('dynamic', 'ip_address')},
            },
        ),
    ]
