# Generated by Django 5.1.15 on 2026-09-27 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0005_category_status"),
        ("dynamic", "0008_dynamiclike"),
        ("tag", "0004_tag_status"),
        ("upload", "0007_uploadfile_upload_created_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dynamic",
            index=models.Index(
                fields=["status", "-created_at"], name="dynamic_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dynamic",
            index=models.Index(
                fields=["status", "-view_count"], name="dynamic_status_views_idx"
            ),
        ),
    ]
