# Generated by Django 5.1.6 on 2025-04-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_alter_tag_options_tag_description_tag_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-created_at'], 'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='create_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='update_time',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='标签名称', max_length=50, unique=True),
        ),
    ]
