# Generated by Django 5.1.6 on 2025-05-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0003_alter_tag_options_rename_create_time_tag_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='status',
            field=models.CharField(choices=[('active', '启用'), ('inactive', '禁用')], default='active', help_text='标签状态', max_length=10),
        ),
    ]
